
main_file: " main.pd"

midi_controllers:
 on/off:
  midi_cc: 77
  value: '2'
  labels: [ '1', '2' ]
 kick: 
  midi_cc: 93
  value: '2'
  labels: [ '1', '2', '3', '4', '5', '6', '7', '8' ]  
 snare: 
  midi_cc: 73
  value: '2'
  labels: [ '1', '2', '3', '4', '5', '6', '7' ]  
 hihat: 
  midi_cc: 75
  value: '2'
  labels: [ '1', '2', '3', '4', '5', '6', '7' ]  
 master volume: 
  midi_cc: 7
  value: 60  
 kick volume: 
  midi_cc: 74
  value: 60  
 snare volume: 
  midi_cc: 71
  value: 60  
 hihat volume: 
  midi_cc: 76
  value: 60  
 tempo:  
  midi_cc: 114
  value: 60  
 map_x: 
  midi_cc: 18
  value: 0
 map_y: 
  midi_cc: 19
  value: 0
 random: 
  midi_cc: 16
  value: 0


